---
deployment:
  tasks:
    - export DEPLOYPATH=/home/minhsss/repositories/minhtrack/
    - /bin/cp -R .next \$DEPLOYPATH
    - /bin/cp -R public \$DEPLOYPATH
    - /bin/cp -R node_modules \$DEPLOYPATH
    - /bin/cp package.json \$DEPLOYPATH
    - /bin/cp next.config.js \$DEPLOYPATH